name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build Backend
      run: mvn clean package -DskipTests

    - name: Copy jar to EC2
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "target/SPKorea_Back-end-0.0.1-SNAPSHOT.jar"
        target: "~/"

    - name: Set executable permission on jar
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: chmod +x ~/SPKorea_Back-end-0.0.1-SNAPSHOT.jar

    - name: Restart Backend on EC2
      uses: appleboy/ssh-action@v0.1.8
      continue-on-error: true
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          pkill -f 'java -jar SPKorea_Back-end-0.0.1-SNAPSHOT.jar' || echo "no process found"
          nohup java -jar SPKorea_Back-end-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
